### PR TITLE
Extensions should be trimmed before use

### PR DESCRIPTION
**Pull request by marswong**

### CODE REVIEW

**Comment by sibiraj-s** [comment]
Thanks for the PR.

Since we are not validating the string, one can easily miss that. So I would recommend that we handle this in the code, rather than mentioning in README.

```js
 getInput('extensions').split(',').map(ext => ext.trim());
```

See https://github.com/sibiraj-s/action-eslint/blob/e540f9c953649609578b617563644a8046a3a528/src/getChangedFiles.ts#L55

Can you make that change?

**Comment by marswong** [comment]
> Thanks for the PR.
> 
> Since we are not validating the string, one can easily miss that. So I would recommend that we handle this in the code, rather than mentioning in README.
> 
> ```js
>  getInput('extensions').split(',').map(ext => ext.trim());
> ```
> 
> See
> 
> https://github.com/sibiraj-s/action-eslint/blob/e540f9c953649609578b617563644a8046a3a528/src/getChangedFiles.ts#L55
> 
> Can you make that change?

sure, just wanna keep args consistent with eslint style before.

**Review by sibiraj-s — APPROVED** [review]
Thanks 👍

**Comment by sibiraj-s** [comment]
Published in [v1.1.1](https://github.com/sibiraj-s/action-eslint/releases/tag/v1.1.1)

**Pull request merged**
