### PR TITLE
Added path-link parameter

### PR DESCRIPTION
**Pull request by dylanparker1**
This parameter allows for a link from the path of node process.cwd() to the location of the node_modules folder if the project structure calls for it. The default is set as an empty string to not affect the path if it isn't needed. This helps account for the lack of ability to use a working-directory while using community actions.

*adding line 82 and 84 in dist/index.js automatically resulted in the rest of the 2600 something changes*

### CODE REVIEW

**Comment by sibiraj-s** [comment]
Thanks for the PR. I am not sure what scenario, we are trying to fix.

All the following should work fine.

- Regular project with npm/yarn <2
- Monorepo with npm/yarn <2
- [working-directory] at job level or step level, for projects in different folder

> adding line 82 and 84 in dist/index.js automatically resulted in the rest of the 2600 something changes

Those are whitespace changes. Make sure you have npm >7/node16

**Comment by dylanparker1** [comment]
The structure for the project I am working on is` {repo}/{level1}/{app}/node_modules`. I have not been able to get process.cwd() to return this path. It always returns `/home/runner/work/{repo}/{repo}`(from what I can tell the base project dir on an actions Ubuntu instance) instead of the full `/home/runner/work/{repo}/{repo}/{level1}/{app}` that I need, even though I use this working directory throughout the action. @sibiraj-s

**Comment by sibiraj-s** [comment]
Do you want to lint only `{repo}/{level1}/{app}` or the whole repo?

**Comment by dylanparker1** [comment]
Only the changed files in `{repo}/{level1}/{app}`

**Comment by sibiraj-s** [comment]
My guess is that you have package.json inside the app folder?

**Comment by dylanparker1** [comment]
@sibiraj-s Correct

**Comment by sibiraj-s** [comment]
```yaml
- name: Install
  run: npm install
  working-directory: `{repo}/{level1}/{app}`
- uses: sibiraj-s/action-eslint@v2
  working-directory: `{repo}/{level1}/{app}`
  with:
      ...
```

this should/must work.

**Comment by dylanparker1** [comment]
Actions will not allow using `working-directory` with a `uses` script, it gives me an error
and using a default at the jobs level like
```
defaults:
  run:
    working-directory: {repo}/{level1}/{app}
```
has not worked either

**Comment by sibiraj-s** [comment]
> Actions will not allow using `working-directory` with a `uses` script, it gives me an error and using a default at the jobs level like
> 
> ```
> defaults:
>   run:
>     working-directory: {repo}/{level1}/{app}
> ```
> 
> has not worked either

Oh. I didn't know that. can you share the error you get?

If the `working-directory` is not compatible with 3rd party actions. It should have worked with `defaults.run`. can you share the error for that as well.

**Comment by sibiraj-s** [comment]
If possible. can you share a reproducible repo? Sorry for me being more hesitant. It's is easy to add first than modify/remove later. Let's figure out why the obvious isn't working first.

**Comment by dylanparker1** [comment]
Error: `The workflow is not valid. .github/workflows/eslint.yml (Line: 26, Col: 9): Unexpected value 'working-directory'`

part of the yaml looks like
```
      - name: Install Dependencies
        working-directory: './{level1}/{app}' #changed on purpose
        run: |
          npm ci
          npm install eslint --save-dev
          npx eslint --init

      - name: Lint Code
        uses: sibiraj-s/action-eslint@v2
(26)    working-directory: './{level1}/{app}'
        with:
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
```

**Comment by sibiraj-s** [comment]
Let me try to create a repository with what you said and work it out.

**Comment by dylanparker1** [comment]
@sibiraj-s Unfortunately I can't share the repo so thank you for trying to recreate the problem. The full yaml would look something like this
```
name: Lint

# on: [pull_request]
on: [workflow_dispatch]  #for testing purposes right now

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Install Dependencies
        working-directory: './{level1}/{app}'
        run: |
          npm ci
          npm install eslint --save-dev
          npx eslint --init

      - name: Lint Code
        uses: sibiraj-s/action-eslint@v2
        with:
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
```

**Comment by dylanparker1** [comment]
If it does come to a merge, and I need to make another pull request to deal with the spacing issue, do you think `working-dir` would be a name that's easier to understand than `path-link`

**Comment by sibiraj-s** [comment]
I think the confusion was with the runner itself. till now I thought working directory would be the `cwd` for a step as well. but when it comes to 3rd party action. the cwd goes back to root. This is very confusing. At-least they should be documented. There are open issues with the runner, but they are un responded.

In our case. `path-link` is not very convincing. we can name it working-directory. but that could be confusing with actual runner option. I am open to this change. In my mind I have been thinking something with option `cwd`

An example of what I am thinking now.

```yml
- uses: 'action-eslint'
  with:
    cwd: ''
```

and in js

```js
const execArgs = [
      'node_modules/eslint/bin/eslint',
      ...files,
      ...eslintArgs,
    ].filter(Boolean)

await exec('node', eslintArgs, { cwd: input.cwd || process.cwd() });
```

Let's come up with something tomorrow. It's very late here.

**Comment by dylanparker1** [comment]
> I think the confusion was with the runner itself. till now I thought working directory would be the `cwd` for a step as well. but when it comes to 3rd party action. the cwd goes back to root. This is very confusing. At-least they should be documented. There are open issues with the runner, but they are un responded.

Yes this was very frustrating for me as well.

`await exec('node', eslintArgs, { cwd: input.cwd || process.cwd() });`
This is more like what I was thinking when I suggested the name change as well

> Let's come up with something tomorrow. It's very late here.

Sounds good

**Comment by dylanparker1** [comment]
I did not have a lot of time to dedicate to a solution but adding 
```
const workingDir = path.join(process.cwd(), getInput('working-directory'), 'node_modules/eslint/bin/eslint');
```
and changing to
```
    await exec('node', [
      workingDir,
      ...files,
      ...eslintArgs,
    ].filter(Boolean));
```
seems like a simple fix to the problem. If there is no working-directory specified it will work as it usually does.  
With an entry in the action.yaml like 
```
working-directory:
    description: 'Specifies working directory that contains node_modules folder'
    required: false
    default: ''

```
I think it makes intuitive sense that specifying a working directory starts at the root of the repo. Without prior knowledge of  the `/home/runner/work/{repo}/{repo}` structure (or other environments available to Actions ) it could be confusing. This solution should also keep any users' builds already using this action intact.

**Comment by sibiraj-s** [comment]
It still leaves with one more problem. Say we are using `working-directory`. and we are executing the eslint from the `app` directory. the paths changed files fetched from github will be still from the root. which will the inner eslint can't resolve. Those paths needs to be changed/fixed relative to the working directory.

**Comment by dylanparker1** [comment]
In my experience this has not been the case. It seems in this case the `working-directory` is really just a pointer to where the eslint binary lives so we can pass it to node. Since `getChangedFiles` returns file paths from the root of the repo, and node is being executed from the root of the repo, they should(and have for me) line up. Did you run into this issue?

**Comment by sibiraj-s** [comment]
You have you eslintrc in the `app` folder right? then running eslint won't be find the config since in the root. if we are changing the cwd to app. then the other files needs to be filtered.

**Comment by dylanparker1** [comment]
I have the solution implemented at dylanparker1/action-eslint@test and it works fine.

Probably because "ESLint will automatically look for them in the directory of the file to be linted, and in successive parent directories all the way up to the root directory of the filesystem" - [docs](https://eslint.org/docs/user-guide/configuring/configuration-files)

**Comment by dylanparker1** [comment]
But also when I create a config using `npx eslint --init` it is in a step that uses the default/working-directory like
```
name: Install Dependencies
        working-directory: './{level1}/{app}'
        run: |
          npm ci
          npm install eslint --save-dev
          npx eslint --init
```
but that should not really matter according to the documentation

**Comment by dylanparker1** [comment]
I think here `working-directory` might also be a bad name choice since its not accurate. It is really just a `path-to-eslint` since the rest of the functionality is the same

**Comment by sibiraj-s** [comment]
> I have the solution implemented at dylanparker1/action-eslint@test and it works fine.
> 
> Probably because "ESLint will automatically look for them in the directory of the file to be linted, and in successive parent directories all the way up to the root directory of the filesystem" - [docs](https://eslint.org/docs/user-guide/configuring/configuration-files)

I was thinking about changing the changing the cwd to `app` directory, since the eslint config will be inside the app directory, running it from the root. Might cause loading plugins to fail at some cases. I will merge this. It can be in master. I will publish it, once I find something concrete for all usecases. 

I am also thinking about switching to `ESLint` node api, allowing the step to be more configurable.

**Comment by sibiraj-s** [comment]
> I think here `working-directory` might also be a bad name choice since its not accurate. It is really just a `path-to-eslint` since the rest of the functionality is the same

Also thinking `npx` + `working_directory` can work. rather than hard loading eslint path.

**Comment by dylanparker1** [comment]
Okay, I'll keep up with the repo and look for your changes. My project is moving forward so I will use a different solution for now. I am sorry that I don't really have time to help you flesh out a full solution, but thanks for taking notice of the issue.

**Pull request merged**
